In [1]:
import cv2
import numpy as np
import copy

#### Initializing parameters

In [2]:

pi = np.zeros((4,4,4))     # intialising pi as 4,4,4 matrix of zeros
r=-1                       # reward for each action
gamma=0.9999               # discount reward factor
grid = np.zeros((4,4))     #grid world matrix
directions= ['UP','DOWN','LEFT','RIGHT']
dir_values=[-1,1,-1,1]

dir_l=list(zip(directions,dir_values)) #list of directions and respected values

grid_old=np.zeros((4,4))


#### Policy evaluation part

In [3]:



def evaluation(pi):
    theta= 0.000001                      #convergence parameter
    delta = 1                         
    while delta > theta:
        delta =0
        grid_old = grid.copy()
    
        for k in range (0,4):                   # running loop within the actual grid
            for l in range (0,4):
                if (k==0 and l==0) or (k==3 and l==3):
                    continue
                
                v=grid[k,l]
                
                grid[k,l]=0
                
                for m in range(0,2):        #updating state values for action UP and DOWN            
                    
                    
                    if k==0 and m==0:
                        
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k,l]))
                        continue
                    
                    elif k==3 and m ==1:
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k,l]))
                    
                    else:
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k+dir_l[m][1],l]))
                    
                for m in range(2,4):        #updating state values for actions LEFT and RIGHT
                    
                    
                    if l==0 and m==2:
                        
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k,l]))
                        continue                
                    elif l==3 and m==3:
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k,l]))
                    
                    else:
                        grid[k,l]+= (pi[k,l,m])*(r+gamma*(grid_old[k,l+dir_l[m][1]]))
                 

                delta = max(delta ,abs(v-grid[k,l]))  # updating canvergence parameter for each state iteration

                
    return grid

#### Policy improvement part

In [10]:

state=False

while state==False:   
    state=True

    for i in range (0,4):                  # iterating through each state
        for j in range(0,4):
            
            if (i==0 and j==0) or (i==3 and j==3):
                    continue
            

            old=pi[i,j,:].copy()        # storing old value of policy for comaparison

            value=np.zeros((4,1))       # defining matrix to find the best future state
                
            for k in range(0,2):         # storing UP and DOWN state values               
                    
                    
                    if i==0 and k==0:
                        
                        value[k,0] = (r+gamma*(grid[i,j]))
                        continue
                    
                    elif i==3 and k ==1:
                        value[k,0] = (r+gamma*(grid[i,j]))
                    
                    else:
                        value[k,0] = (r+gamma*(grid[i+dir_l[k][1],j]))
                        
            

            
                
            for k in range(2,4):         # storing LEFT and RIGHT state values
                    
                    
                    if j==0 and k==2:
                        
                        value[k,0] = (r+gamma*(grid[i,j]))
                        continue                
                    elif j==3 and k==3:
                        value[k,0] = (r+gamma*(grid[i,j]))
                    
                    else:
                        value[k,0] = (r+gamma*(grid[i,j+dir_l[k][1]]))
                
            
            pi[i,j,:]=0            # initilising all policy values for a state to zero for further update
            
            
            index = np.zeros((4))  # index matrix to find out the idex of the maximum states
            
            max_value = np.max(value,axis=0)
            
            
            

            for m in range(0,4):        #finding the indexes of maximum value in the value matrix and seting-
                if value[m,0]==max_value: # corresponding index in the index matrix as index + 1
                    index[m] = m+1


            index_non_null = np.where(index!=0) # matrix of indexes of non null values in index matrix
            
            l, size = np.shape(index_non_null)  # size of index_non_null tells how many optimal actions are possible
            
            
            
            for n in index_non_null:
                pi[i,j,n]= (1/size)           # setting the policy value of actions as per index_non_null values to probability of that action
            

            if all(old != pi[i,j,:]):  #stability condition
                state= False

    if (state == False):
        grid=evaluation(pi)    #passing updated policy matrix to evaluation in case of instability of solution


print(grid)
print(pi)

[[ 0.         -1.         -1.9999     -2.99970001]
 [-1.         -1.9999     -2.99970001 -1.9999    ]
 [-1.9999     -2.99970001 -1.9999     -1.        ]
 [-2.99970001 -1.9999     -1.          0.        ]]
[[[0.   0.   0.   0.  ]
  [0.   0.   1.   0.  ]
  [0.   0.   1.   0.  ]
  [0.   0.5  0.5  0.  ]]

 [[1.   0.   0.   0.  ]
  [0.5  0.   0.5  0.  ]
  [0.25 0.25 0.25 0.25]
  [0.   1.   0.   0.  ]]

 [[1.   0.   0.   0.  ]
  [0.25 0.25 0.25 0.25]
  [0.   0.5  0.   0.5 ]
  [0.   1.   0.   0.  ]]

 [[0.5  0.   0.   0.5 ]
  [0.   0.   0.   1.  ]
  [0.   0.   0.   1.  ]
  [0.   0.   0.   0.  ]]]
