In [1]:
import cv2
import numpy as np
import copy

In [2]:
def evaluation(pi):
    
    directions= ['UP','DOWN','LEFT','RIGHT']
    dir_values=[-1,1,-1,1]

    dir_l=list(zip(directions,dir_values))
    grid = np.zeros((6,6))
      # creating a grid of 4 by 4 with one extra cell in the periphery  
    #grid[1:5,1:5] = np.zeros((4,4))  # random intitialisation of the state values
    #grid[1,1]=grid[4,4]=0  # assigning the terminal state value as zero
    v=0   # comparision matrix, used to find convergence of solution
    r=-1      # reward for each action
    gamma=0.99# discount reward factor
    theta= 0.000001  # convergence error 
    grid_old=np.zeros((6,6))
    count=0
    while True:
        delta =0
        for i in range(0,6):
            if i==1:
                    grid[i-1,:] = grid[i,:]

            if i==4:

                    grid[i+1,:] = grid[i,:]# updating the periphery values of the 6 by 6 grid
        for j in range(0,6):
            if j==1:
                    grid[:,j-1]=grid[:,j]

            if j==4:
                    grid[:,j+1]=grid[:,j]



        grid_old=grid

        for k in range (1,5):                   # running loop within the actual grid
            for l in range (1,5):
                if (k==1 and l==1) or (k==4 and l==4):
                    continue
                
                v=grid[k,l]
                
                grid[k,l]= pi[k-1,l-1,0]*(r+gamma*(grid_old[k-1,l]))
                
                for m in range(1,2):
                    
                    grid[k,l]+= (pi[k-1,l-1,m])*(r+gamma*(grid_old[k+dir_l[m][1],l]))
                    
                for m in range(2,4):
                    grid[k,l]+= (pi[k-1,l-1,m])*(r+gamma*(grid_old[k,l+dir_l[m][1]]))
                #updating the State values for all states except terminal 

                delta = max(delta ,abs(v-grid[k,l]))


        if (delta<theta): #checking for convergenge of solution
            #final comparison matrix
            break

     # final state value matrix for all states 
    
    return grid

In [3]:
pi = (np.ones((4,4,4))*0.25)
grid=evaluation(pi)


In [10]:

state=False
while state==False:
    state=True
    directions= ['UP','DOWN','LEFT','RIGHT']
    dir_values=[-1,1,-1,1]
    r=-1
    gamma=0.99
    dir_l=list(zip(directions,dir_values))

    for i in range (1,5):
        for j in range(1,5):

            old=pi[i-1,j-1,:]
            pi[i-1,j-1,:]=0

            value=np.zeros((4,1))

            if (i==1 and j==1) or (i==4 and j==4):
                    continue

            for k in range(0,2):

                value[k,0]= r+gamma*(grid[i+dir_l[k][1],j])

            for k in range(2,4):

                value[k,0]= r+gamma*(grid[i,j+dir_l[k][1]])

            index= np.argmax(value,axis=1)
            for m in index:

                pi[i-1,j-1,m]=(1/index.size)
            
            comparison = old==pi[i-1,j-1,:]


            if (~comparison.all()):
                
                state= False

    if (state == False):
        grid=evaluation(pi)

        
print(grid)
print(pi)

[[  0.           0.         -11.94519995 -16.96108302 -18.60541702
  -18.60541702]
 [  0.           0.         -11.94520053 -16.96108384 -18.60541793
  -18.60541702]
 [-11.94519995 -11.94520053 -15.31675016 -16.97752783 -16.96108458
  -16.96108384]
 [-16.96108302 -16.96108384 -16.97752783 -15.31675079 -11.94520152
  -11.94520105]
 [-18.60541702 -18.60541793 -16.96108458 -11.94520152   0.
    0.        ]
 [-18.60541702 -18.60541702 -16.96108384 -11.94520105   0.
    0.        ]]
[[[0.   0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]]

 [[0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]]

 [[0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]]

 [[0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.25 0.   0.   0.  ]
  [0.   0.   0.   0.  ]]]
True


In [7]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]

zipped = zip(list_a, list_b) # Output: Zip Object. <zip at 0x4c10a30>

 # TypeError: object of type 'zip' has no len()

 # TypeError: 'zip' object is not subscriptable

list_c = list(zipped) #Output: [(1, 4), (2, 5), (3, 6)]

print(list_c[1][0]) # Output []... Output is empty list becuase by the above statement zip got exhausted.

2
