In [28]:
import cv2
import numpy as np
import copy

#### Initialising all the parametric values

In [29]:
theta=0.01  
delta =1
grid = np.random.rand(4,4)  # random initialisation of the grid world
grid[0,0]=grid[3,3]=0 
r=-1                        # reward parameter 
gamma=0.999                 # discounting factor
pi = np.zeros((4,4,4))      # policy matrix

directions= ['UP','DOWN','LEFT','RIGHT']
dir_values=[-1,1,-1,1]

dir_l=list(zip(directions,dir_values))  # list of action along with their values -1 for UP etc.


#### Maximising state values

In [30]:
while delta > theta:                # loop condition
        delta =0
        count+=1
    
    
        for k in range (0,4):                   # running loop within all state values
            for l in range (0,4):
                if (k==0 and l==0) or (k==3 and l==3):
                    continue
                
                grid_eval=np.zeros((4,1))       # evaluation grid 
                
                v=grid[k,l]                     # temporary value
                
                
                for m in range(0,2):            # storing values for actions UP and DOWN           
                    
                    
                    if k==0 and m==0:
                        
                        grid_eval[m,0] = (r+gamma*(grid[k,l]))
                        continue
                    
                    elif k==3 and m ==1:
                        grid_eval[m,0] = (r+gamma*(grid[k,l]))
                    
                    else:
                        grid_eval[m,0] = (r+gamma*(grid[k+dir_l[m][1],l]))
                    
                for m in range(2,4):             # storing values for actions LEFT and RIGHT
                    
                    
                    if l==0 and m==2:
                        
                        grid_eval[m,0] = (r+gamma*(grid[k,l]))
                        continue                
                    elif l==3 and m==3:
                        grid_eval[m,0] = (r+gamma*(grid[k,l]))
                    
                    else:
                        grid_eval[m,0] = (r+gamma*(grid[k,l+dir_l[m][1]]))
                
                grid[k,l] = np.max(grid_eval)       # assigning max value to the current state grid[k,l]
         

                delta = max(delta ,abs(v-grid[k,l]))  # updating the delta value


print(grid) #final state after setting maximising state values 


[[ 0.       -1.       -1.999    -2.997001]
 [-1.       -1.999    -2.997001 -1.999   ]
 [-1.999    -2.997001 -1.999    -1.      ]
 [-2.997001 -1.999    -1.        0.      ]]


#### Finding optimal policy 

In [31]:
for k in range(0,4):
    for l in range(0,4):
        if (k==0 and l==0) or (k==3 and l==3):
                    continue
                
        grid_eval=np.zeros((4,1))                

        for m in range(0,2):                  


            if k==0 and m==0:

                grid_eval[m,0] = (r+gamma*(grid[k,l]))
                continue

            elif k==3 and m ==1:
                grid_eval[m,0] = (r+gamma*(grid[k,l]))

            else:
                grid_eval[m,0] = (r+gamma*(grid[k+dir_l[m][1],l]))

        for m in range(2,4):


            if l==0 and m==2:

                grid_eval[m,0] = (r+gamma*(grid[k,l]))
                continue                
            elif l==3 and m==3:
                grid_eval[m,0] = (r+gamma*(grid[k,l]))

            else:
                grid_eval[m,0] = (r+gamma*(grid[k,l+dir_l[m][1]]))

        pi[k,l,np.argmax(grid_eval,axis=0)]=1   # setting action which leads to max state value as 1
        
print(pi)
# the optimal policy matrix is a 3D 4,4,4 matrix with first two indexes representing  rows and columns and last 
#index representing the action taken in order UP, DOWN, LEFT and RIGHT 

[[[0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 0.]]]
