In [0]:
import numpy as np

In [0]:
#creating a grid environment
def gridEnv(curr_state,action):
  # In the 4*4 grid world state 0 and state 15 are terminal states
  if(curr_state==0 or curr_state==15):
    next_state=curr_state
    reward=0
  else:
    #action 0 --> UP, action 1 --> DOWN, action 2 --> RIGHT, action 3 --> LEFT
    #if the action results in the agent coming out of the grid then the curr_state will not change
    reward=-1
    if(action==0):
      next_state=curr_state-4
      if(next_state<0):
        next_state=curr_state
    elif(action==1):
      next_state=curr_state+4
      if(next_state>=16):
        next_state=curr_state
    elif(action==2):
      if((curr_state+1)%4==0):
        next_state=curr_state
      else:
        next_state=curr_state+1
    elif(action==3):
      if(curr_state%4==0):
        next_state=curr_state
      else:
        next_state=curr_state-1
#if the next_state is the terminanl state the reward is 0 otherwise -1
  #In this grid world the state transition probability for the given action and state is 1.
  items=[1,next_state,reward]

  return items

In [0]:
def valueIteration(policy,gamma=0.999,theta=0.0000001):
    #Initializing the value fucntion as zero
    vf=np.zeros(16)
    while(True):
        delta=0
        #Iterating over all the states
        for curr_state in range(16):
            avp=np.zeros(4)
            for curr_action in range(4):
                stateTprob, next_state, reward = gridEnv(curr_state, curr_action)
                avp[curr_action] = stateTprob*(reward+gamma*vf[next_state])
            b_action=np.argmax(avp)
            #taking the maximum value function 
            b_vf=np.max(avp)
            #Updating the policy
            policy[curr_state]=np.eye(4)[b_action]
            delta=max(delta,np.abs(vf[curr_state]-b_vf))
            #Assiging the state its new value function
            vf[curr_state]=b_vf
        #breaking the loop if delta is less than theta
        if(delta<theta):
            break
    return policy,vf

In [0]:
#initializing random policy where each action has equal probability
policy = np.ones([16, 4])/4
policy,vf= valueIteration(policy)
print(f'Optimal Policy:\n\n {policy}\n')
print(f'Optimal Value function:\n\n {vf.reshape(4, 4)}')


Optimal Policy:

 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

Optimal Value function:

 [[ 0.       -1.       -1.999    -2.997001]
 [-1.       -1.999    -2.997001 -1.999   ]
 [-1.999    -2.997001 -1.999    -1.      ]
 [-2.997001 -1.999    -1.        0.      ]]
